# Tell Spring where to get the data from
spring:
    datasource:
        #url: jdbc:h2:mem:moviesdb      # name of your db - if you want  to persist data between runs you can specify a file path: jdbc:h2:file:[path]
        #username: sa                   # this is the default username for h2
        #password:                      # optional for h2
        #driverClassName: org.h2.Driver # jdbs uses this to connect to database

        #postgres
        url: jdbc:postgresql://localhost:5432/warehouse_management
        username: postgres
        password: skillstorm123
    output:
        ansi:
            enabled: ALWAYS
    #jpa:
        #database-platform: org.hibernate.dialect.H2Dialect   # tells spring data jpa that we are using h2 database
        #defer-datasource-initialization: true                # tells JPA to wait until hibernate has initialized before loading the data to h2

#server:
    #port: 8282     # changes port number for server

# sets your logging level - default INFO
logging:
    level:
        com:
            skillstorm: debug